### ISSUE TITLE
Treetap produces rubber sap on all tiles of the ic2 rubber tree?

### ISSUE THREAD

**Issue by wormzjl** [TTFTCUTS/CuttingEdge#2]
The treetap seem to be working on any block of rubber wood on the ic2 rubber tree, is it possible to make it only produces rubber sap on tiles with a extraction point (that yellow dot)?

**Comment by TTFTCUTS** [comment]
The rate is based upon the number of leaves on the tree rather than the tap points, and is split between multiple taps on the same tree. Working as intended.
