### ISSUE TITLE
Evaporator/Tree Tapping Kit does not save tank content (SinglePlayer)

### ISSUE THREAD

**Issue by samtrion** [TTFTCUTS/CuttingEdge#3]
Version CuttingEdge-1.7.10-0.1.0-2.jar

**Comment by TTFTCUTS** [comment]
It... really should do... I'm sure it did in dev. Will investigate.

**Comment by TTFTCUTS** [comment]
I worked this one out - I wasn't paying close enough attention to the loading stuff where the world is null, so it was throwing an NPE on load and discarding the saved data.

**Comment by TTFTCUTS** [comment]
Fixed in version 3.
